using System;
using System.Collections.Generic;
using Rage;

namespace DamageTrackingFramework
{
    internal static class Lookups
    {
        internal static readonly Dictionary<BoneId, (Limb limb, BodyRegion bodyRegion)>
            BoneLookup =
                new Dictionary<BoneId, (Limb limb, BodyRegion bodyRegion)>
                {
                    [BoneId.Root] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.LeftThumb1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftThumb2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftRingFinger1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftRingFinger2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftPinky1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftPinky2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftIndexFinger1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftIndexFinger2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftMiddleFinger1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftMiddleFinger2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.RightClavicle] = (Limb.Chest, BodyRegion.Torso),
                    [BoneId.Pelvis] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.LeftFoot] = (Limb.LeftLeg, BodyRegion.Legs),
                    [BoneId.LeftHand] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.Spine] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.RightPhFoot] = (Limb.RightLeg, BodyRegion.Legs),
                    [BoneId.Spine1] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.Spine2] = (Limb.Chest, BodyRegion.Torso),
                    [BoneId.Spine3] = (Limb.Chest, BodyRegion.Torso),
                    [BoneId.LeftThumb0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftIndexFinger0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftMiddleFinger0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftRingFinger0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftPinky0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.RightForearm] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightPhHand] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.Head] = (Limb.Head, BodyRegion.Head),
                    [BoneId.RightCalf] = (Limb.RightLeg, BodyRegion.Legs),
                    [BoneId.Neck] = (Limb.Head, BodyRegion.Head),
                    [BoneId.RightUpperArm] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.LeftUpperArm] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.RightThigh] = (Limb.RightLeg, BodyRegion.Legs),
                    [BoneId.RightFoot] = (Limb.RightLeg, BodyRegion.Legs),
                    [BoneId.RightHand] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.SpineRoot] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.LeftPhFoot] = (Limb.LeftLeg, BodyRegion.Arms),
                    [BoneId.LeftThigh] = (Limb.LeftLeg, BodyRegion.Legs),
                    [BoneId.RightThumb0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightIndexFinger0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightMiddleFinger0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightRingFinger0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightPinky0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.LeftPhHand] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftForeArm] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftCalf] = (Limb.LeftLeg, BodyRegion.Legs),
                    [BoneId.RightThumb1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightThumb2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightRingFinger1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightRingFinger2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightPinky1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightPinky2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightIndexFinger1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightIndexFinger2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightMiddleFinger1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightMiddleFinger2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.LeftClavicle] = (Limb.Chest, BodyRegion.Torso),
                };

        internal static readonly Dictionary<WeaponHash, (string Name, DamageGroup DamageType, DamageType WeaponGroup)>
            WeaponLookup =
                new Dictionary<WeaponHash, (string Name, DamageGroup DamageType, DamageType WeaponGroup)>
                {
                    [WeaponHash.AntiqueCavalryDagger] =
                        ("Antique Cavalry Dagger", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.BaseballBat] = ("Baseball Bat", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Bottle] = ("Bottle", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Crowbar] = ("Crowbar", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Fist] = ("Fist", DamageGroup.Melee, DamageType.Unarmed),
                    [WeaponHash.Flashlight] = ("Flashlight", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.GolfClub] = ("Golf Club", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Hammer] = ("Hammer", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Hatchet] = ("Hatchet", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Knuckle] = ("Knuckle", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Knife] = ("Knife", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Machete] = ("Machete", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Switchblade] = ("Switchblade", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Nightstick] = ("Nightstick", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.PipeWrench] = ("Pipe Wrench", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.BattleAxe] = ("Battle Axe", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.PoolCue] = ("Pool Cue", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.StoneHatchet] = ("Stone Hatchet", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Pistol] = ("Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.PistolMK2] = ("Pistol MK2", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.CombatPistol] = ("Combat Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.APPistol] = ("AP Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.StunGun] = ("Stun Gun", DamageGroup.LessThanLethal, DamageType.LessThanLethal),
                    [WeaponHash.Pistol50] = ("Pistol .50", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.SNSPistol] = ("SNS Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.SNSPistolMK2] = ("SNS Pistol MK2", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.HeavyPistol] = ("Heavy Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.VintagePistol] = ("Vintage Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.FlareGun] = ("Flare Gun", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.MarksmanPistol] = ("Marksman Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.HeavyRevolver] = ("Heavy Revolver", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.HeavyRevolverMK2] = ("Heavy Revolver MK2", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.DoubleAction] = ("Double Action", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Up_n_Atomizer] = ("Up-n-Atomizer", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.MicroSMG] = ("Micro SMG", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.SMG] = ("SMG", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.SMGMK2] = ("SMG MK2", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.AssaultSMG] = ("Assault SMG", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.CombatPDW] = ("Combat PDW", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.MachinePistol] = ("Machine Pistol", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.MiniSMG] = ("Mini SMG", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.UnholyHellbringer] = ("Unholy Hellbringer", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.PumpShotgun] = ("Pump Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.PumpShotgunMK2] = ("Pump Shotgun MK2", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Sawed_OffShotgun] = ("Sawed-Off Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.AssaultShotgun] = ("Assault Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.BullpupShotgun] = ("Bullpup Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Musket] = ("Musket", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.HeavyShotgun] = ("Heavy Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.DoubleBarrelShotgun] =
                        ("Double Barrel Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.SweeperShotgun] = ("Sweeper Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.AssaultRifle] = ("Assault Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.AssaultRifleMK2] = ("Assault Rifle MK2", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.CarbineRifle] = ("Carbine Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.CarbineRifleMK2] = ("Carbine Rifle MK2", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.AdvancedRifle] = ("Advanced Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.SpecialCarbine] = ("Special Carbine", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.SpecialCarbineMK2] = ("Special Carbine MK2", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.BullpupRifle] = ("Bullpup Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.BullpupRifleMK2] = ("Bullpup Rifle MK2", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.CompactRifle] = ("Compact Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.MG] = ("MG", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.CombatMG] = ("Combat MG", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.CombatMGMK2] = ("Combat MG MK2", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.GusenbergSweeper] = ("Gusenberg Sweeper", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.SniperRifle] = ("Sniper Rifle", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.HeavySniper] = ("Heavy Sniper", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.HeavySniperMK2] = ("Heavy Sniper MK2", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.MarksmanRifle] = ("Marksman Rifle", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.MarksmanRifleMK2] = ("Marksman Rifle MK2", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.RPG] = ("RPG", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.GrenadeLauncher] = ("Grenade Launcher", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.SmokeGrenadeLauncher] = ("Smoke Grenade Launcher", DamageGroup.NonDamaging,
                        DamageType.Launcher),
                    [WeaponHash.Minigun] = ("Minigun", DamageGroup.Bullet, DamageType.Launcher),
                    [WeaponHash.FireworkLauncher] = ("Firework Launcher", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Railgun] = ("Railgun", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.HomingLauncher] = ("Homing Launcher", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.CompactGrenadeLauncher] = ("Compact Grenade Launcher", DamageGroup.Explosion,
                        DamageType.Launcher),
                    [WeaponHash.RayMinigun] = ("Ray Minigun", DamageGroup.Bullet, DamageType.Launcher),
                    [WeaponHash.Grenade] = ("Grenade", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.BZGas] = ("BZ Gas", DamageGroup.Gas, DamageType.Gas),
                    [WeaponHash.SmokeGrenade] =
                        ("Smoke Grenade", DamageGroup.NonDamaging, DamageType.ThrowableNonLethal),
                    [WeaponHash.Flare] = ("Flare", DamageGroup.NonDamaging, DamageType.ThrowableNonLethal),
                    [WeaponHash.Molotov] = ("Molotov", DamageGroup.Fire, DamageType.Fire),
                    [WeaponHash.StickyBomb] = ("Sticky Bomb", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.ProximityMine] = ("Proximity Mine", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.Snowball] = ("Snowball", DamageGroup.NonDamaging, DamageType.ThrowableNonLethal),
                    [WeaponHash.PipeBomb] = ("Pipe Bomb", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.Baseball] = ("Baseball", DamageGroup.NonDamaging, DamageType.ThrowableNonLethal),
                    [WeaponHash.JerryCan] = ("Jerry Can", DamageGroup.NonDamaging, DamageType.Misc),
                    [WeaponHash.FireExtinguisher] = ("Fire Extinguisher", DamageGroup.NonDamaging, DamageType.Misc),
                    [WeaponHash.Parachute] = ("Parachute", DamageGroup.Unknown, DamageType.Unknown),
                    [WeaponHash.ElectricFence] = ("Electric Fence", DamageGroup.Environmental, DamageType.Electric),
                    [WeaponHash.HitbyWaterCannon] =
                        ("Hit by Water Cannon", DamageGroup.WaterCannon, DamageType.WaterCannon),
                    [WeaponHash.RammedbyCar] = ("Rammed by Car", DamageGroup.Vehicle, DamageType.Vehicle),
                    [WeaponHash.RunOverbyCar] = ("Run Over by Car", DamageGroup.Vehicle, DamageType.Vehicle),
                    [WeaponHash.Fall] = ("Fall", DamageGroup.Fall, DamageType.Fall),
                    [WeaponHash.Animal] = ("Animal", DamageGroup.Animal, DamageType.Animal),
                    [WeaponHash.AirstrikeRocket] = ("Airstrike Rocket", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Bleeding] = ("Bleeding", DamageGroup.Medical, DamageType.Medical),
                    [WeaponHash.Briefcase] = ("Briefcase", DamageGroup.Unknown, DamageType.Unknown),
                    [WeaponHash.Briefcase02] = ("Briefcase 02", DamageGroup.Unknown, DamageType.Unknown),
                    [WeaponHash.Cougar] = ("Cougar", DamageGroup.Animal, DamageType.Animal),
                    [WeaponHash.BarbedWire] = ("Barbed Wire", DamageGroup.Environmental, DamageType.BarbedWire),
                    [WeaponHash.Drowning] = ("Drowning", DamageGroup.Drowning, DamageType.Drowning),
                    [WeaponHash.DrowningInVehicle] = ("Drowning In Vehicle", DamageGroup.Drowning, DamageType.Drowning),
                    [WeaponHash.Explosion] = ("Explosion", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.Exhaustion] = ("Exhaustion", DamageGroup.Medical, DamageType.Medical),
                    [WeaponHash.Fire] = ("Fire", DamageGroup.Fire, DamageType.Fire),
                    [WeaponHash.HeliCrash] = ("Heli Crash", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.VehicleRocket] = ("Vehicle Rocket", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.VehicleAkulaBarrage] = ("Vehicle Akula Barrage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleAkulaMinigun] = ("Vehicle Akula Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleAkulaMissile] = ("Vehicle Akula Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleAkulaTurretDual] = ("Vehicle Akula Turret Dual", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleAkulaTurretSingle] = ("Vehicle Akula Turret Single", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleAPCCannon] = ("Vehicle APC Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleAPCMG] = ("Vehicle APC MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleAPCMissile] = ("Vehicle APC Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleArdentMG] = ("Vehicle Ardent MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleAvengerCannon] = ("Vehicle Avenger Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleBarrageRearGL] = ("Vehicle Barrage Rear GL", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleBarrageRearMG] = ("Vehicle Barrage Rear MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleBarrageRearMinigun] = ("Vehicle Barrage Rear Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleBarrageTopMG] = ("Vehicle Barrage Top MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleBarrageTopMinigun] = ("Vehicle Barrage Top Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleBombushkaCannon] = ("Vehicle Bombushka Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleBombushkaDualMG] = ("Vehicle Bombushka Dual MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleCannonBlazer] = ("Vehicle Cannon Blazer", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleCaracaraMG] =
                        ("Vehicle Caracara MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleCaracaraMinigun] = ("Vehicle Caracara Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleChernoMissile] = ("Vehicle Cherno Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleCometMG] = ("Vehicle Comet MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleDeluxoMG] = ("Vehicle Deluxo MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleDeluxoMissile] = ("Vehicle Deluxo Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleDogfighterMG] = ("Vehicle Dogfighter MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleDogfighterMissile] = ("Vehicle Dogfighter Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleDuneGrenadeLauncher] = ("Vehicle Dune Grenade Launcher", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleDuneMG] = ("Vehicle Dune MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleDuneMinigun] =
                        ("Vehicle Dune Minigun", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleEnemyLaser] = ("Vehicle Enemy Laser", DamageGroup.Unknown, DamageType.Unknown),
                    [WeaponHash.VehicleHackerMissile] = ("Vehicle Hacker Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleHackerMissileHoming] = ("Vehicle Hacker Missile Homing", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleHalftrackDualMG] = ("Vehicle Halftrack Dual MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleHalftrackQuadMG] = ("Vehicle Halftrack Quad MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleHavokMinigun] = ("Vehicle Havok Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleHunterBarrage] = ("Vehicle Hunter Barrage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleHunterCannon] = ("Vehicle Hunter Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleHunterMG] = ("Vehicle Hunter MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleHunterMissile] = ("Vehicle Hunter Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleInsurgentMinigun] = ("Vehicle Insurgent Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleKhanjaliCannon] = ("Vehicle Khanjali Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleKhanjaliCannonHeavy] = ("Vehicle Khanjali Cannon Heavy", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleKhanjaliGL] = ("Vehicle Khanjali GL", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleKhanjaliMG] =
                        ("Vehicle Khanjali MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleMenacerMG] =
                        ("Vehicle Menacer MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleMicrolightMG] = ("Vehicle Microlight MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleMobileopsCannon] = ("Vehicle Mobileops Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleMogulDualNose] = ("Vehicle Mogul Dual Nose", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleMogulDualTurret] = ("Vehicle Mogul Dual Turret", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleMogulNose] =
                        ("Vehicle Mogul Nose", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleMogulTurret] =
                        ("Vehicle Mogul Turret", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleMule4MG] = ("Vehicle Mule4 MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleMule4Missile] = ("Vehicle Mule4 Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleMule4TurretGL] = ("Vehicle Mule4 Turret GL", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleNightsharkMG] = ("Vehicle Nightshark MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleNoseTurretValkyrie] = ("Vehicle Nose Turret Valkyrie", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleOppressorMG] =
                        ("Vehicle Oppressor MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleOppressorMissile] = ("Vehicle Oppressor Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleOppressor2Cannon] = ("Vehicle Oppressor2 Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleOppressor2MG] = ("Vehicle Oppressor2 MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleOppressor2Missile] = ("Vehicle Oppressor2 Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehiclePlaneRocket] = ("Vehicle Plane Rocket", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehiclePlayerBuzzard] = ("Vehicle Player Buzzard", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehiclePlayerLazer] = ("Vehicle Player Lazer", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehiclePlayerSavage] = ("Vehicle Player Savage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehiclePounder2Barrage] = ("Vehicle Pounder2 Barrage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehiclePounder2GL] = ("Vehicle Pounder2 GL", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehiclePounder2Mini] = ("Vehicle Pounder2 Mini", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehiclePounder2Missile] = ("Vehicle Pounder2 Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleRadar] = ("Vehicle Radar", DamageGroup.NonDamaging, DamageType.NonDamaging),
                    [WeaponHash.VehicleRevolterMG] =
                        ("Vehicle Revolter MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleRogueCannon] = ("Vehicle Rogue Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleRogueMG] = ("Vehicle Rogue MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleRogueMissile] = ("Vehicle Rogue Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleRuinerBullet] = ("Vehicle Ruiner Bullet", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleRuinerRocket] = ("Vehicle Ruiner Rocket", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleSavestraMG] =
                        ("Vehicle Savestra MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleScramjetMG] =
                        ("Vehicle Scramjet MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleScramjetMissile] = ("Vehicle Scramjet Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleSeabreezeMG] =
                        ("Vehicle Seabreeze MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleSearchlight] = ("Vehicle Searchlight", DamageGroup.NonDamaging,
                        DamageType.NonDamaging),
                    [WeaponHash.VehicleSpaceRocket] = ("Vehicle Space Rocket", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleSpeedo4MG] =
                        ("Vehicle Speedo4 MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleSpeedo4TurretMG] = ("Vehicle Speedo4 Turret MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleSpeedo4TurretMini] = ("Vehicle Speedo4 Turret Mini", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleStrikeforceBarrage] = ("Vehicle Strikeforce Barrage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleStrikeforceCannon] = ("Vehicle Strikeforce Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleStrikeforceMissile] = ("Vehicle Strikeforce Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleSubcarMG] = ("Vehicle Subcar MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleSubcarMissile] = ("Vehicle Subcar Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleSubcarTorpedo] = ("Vehicle Subcar Torpedo", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleTampaDualMinigun] = ("Vehicle Tampa Dual Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTampaFixedMinigun] = ("Vehicle Tampa Fixed Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTampaMissile] = ("Vehicle Tampa Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleTampaMortar] = ("Vehicle Tampa Mortar", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleTank] = ("Vehicle Tank", DamageGroup.Explosion, DamageType.VehicleLauncher),
                    [WeaponHash.VehicleTechnicalMinigun] = ("Vehicle Technical Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleThrusterMG] =
                        ("Vehicle Thruster MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleThrusterMissile] = ("Vehicle Thruster Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleTrailerDualaa] = ("Vehicle Trailer Dualaa", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleTrailerMissile] = ("Vehicle Trailer Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleTrailerQuadMG] = ("Vehicle Trailer Quad MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTulaDualMG] =
                        ("Vehicle Tula Dual MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTulaMG] = ("Vehicle Tula MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTulaMinigun] =
                        ("Vehicle Tula Minigun", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTulaNoseMG] =
                        ("Vehicle Tula Nose MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTurretBoxville] = ("Vehicle Turret Boxville", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTurretInsurgent] = ("Vehicle Turret Insurgent", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTurretLimo] =
                        ("Vehicle Turret Limo", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTurretTechnical] = ("Vehicle Turret Technical", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleTurretValkyrie] = ("Vehicle Turret Valkyrie", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleVigilanteMG] =
                        ("Vehicle Vigilante MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleVigilanteMissile] = ("Vehicle Vigilante Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.VehicleViserisMG] =
                        ("Vehicle Viseris MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.VehicleVolatolDualMG] = ("Vehicle Volatol Dual MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.VehicleWaterCannon] = ("Vehicle Water Cannon", DamageGroup.WaterCannon,
                        DamageType.WaterCannon)
                };
    };
}