using System.Collections.Generic;
using DamageTrackerLib.DamageInfo;

namespace DamageTrackerLib
{
    public static class Lookups
    {
        public static readonly Dictionary<BoneId, (Limb limb, BodyRegion bodyRegion)>
            BoneLookup =
                new Dictionary<BoneId, (Limb limb, BodyRegion bodyRegion)>
                {
                    [BoneId.Root] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.LeftThumb1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftThumb2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftRingFinger1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftRingFinger2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftPinky1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftPinky2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftIndexFinger1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftIndexFinger2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftMiddleFinger1] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftMiddleFinger2] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.RightClavicle] = (Limb.Chest, BodyRegion.Torso),
                    [BoneId.Pelvis] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.LeftFoot] = (Limb.LeftLeg, BodyRegion.Legs),
                    [BoneId.LeftHand] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.Spine] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.RightPhFoot] = (Limb.RightLeg, BodyRegion.Legs),
                    [BoneId.Spine1] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.Spine2] = (Limb.Chest, BodyRegion.Torso),
                    [BoneId.Spine3] = (Limb.Chest, BodyRegion.Torso),
                    [BoneId.LeftThumb0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftIndexFinger0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftMiddleFinger0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftRingFinger0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftPinky0] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.RightForearm] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightPhHand] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.Head] = (Limb.Head, BodyRegion.Head),
                    [BoneId.RightCalf] = (Limb.RightLeg, BodyRegion.Legs),
                    [BoneId.Neck] = (Limb.Head, BodyRegion.Head),
                    [BoneId.RightUpperArm] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.LeftUpperArm] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.RightThigh] = (Limb.RightLeg, BodyRegion.Legs),
                    [BoneId.RightFoot] = (Limb.RightLeg, BodyRegion.Legs),
                    [BoneId.RightHand] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.SpineRoot] = (Limb.Stomach, BodyRegion.Torso),
                    [BoneId.LeftPhFoot] = (Limb.LeftLeg, BodyRegion.Arms),
                    [BoneId.LeftThigh] = (Limb.LeftLeg, BodyRegion.Legs),
                    [BoneId.RightThumb0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightIndexFinger0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightMiddleFinger0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightRingFinger0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightPinky0] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.LeftPhHand] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftForeArm] = (Limb.LeftArm, BodyRegion.Arms),
                    [BoneId.LeftCalf] = (Limb.LeftLeg, BodyRegion.Legs),
                    [BoneId.RightThumb1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightThumb2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightRingFinger1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightRingFinger2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightPinky1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightPinky2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightIndexFinger1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightIndexFinger2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightMiddleFinger1] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.RightMiddleFinger2] = (Limb.RightArm, BodyRegion.Arms),
                    [BoneId.LeftClavicle] = (Limb.Chest, BodyRegion.Torso),
                };

        public static readonly Dictionary<WeaponHash, (string Name, DamageGroup DamageGroup, DamageType DamageType)>
            WeaponLookup =
                new Dictionary<WeaponHash, (string Name, DamageGroup DamageGroup, DamageType DamageType)>
                {
                    [WeaponHash.Antique_Cavalry_Dagger] =
                        ("Antique Cavalry Dagger", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Baseball_Bat] = ("Baseball Bat", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Bottle] = ("Bottle", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Crowbar] = ("Crowbar", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Fist] = ("Fist", DamageGroup.Melee, DamageType.Unarmed),
                    [WeaponHash.Flashlight] = ("Flashlight", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Golf_Club] = ("Golf Club", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Hammer] = ("Hammer", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Hatchet] = ("Hatchet", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Knuckle] = ("Knuckle", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Knife] = ("Knife", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Machete] = ("Machete", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Switchblade] = ("Switchblade", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Nightstick] = ("Nightstick", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Pipe_Wrench] = ("Pipe Wrench", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Battle_Axe] = ("Battle Axe", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Pool_Cue] = ("Pool Cue", DamageGroup.Melee, DamageType.MeleeBlunt),
                    [WeaponHash.Stone_Hatchet] = ("Stone Hatchet", DamageGroup.Melee, DamageType.MeleeStab),
                    [WeaponHash.Pistol] = ("Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Pistol_MK2] = ("Pistol MK2", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Combat_Pistol] = ("Combat Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.APPistol] = ("AP Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Stun_Gun] = ("Stun Gun", DamageGroup.LessThanLethal, DamageType.LessThanLethal),
                    [WeaponHash.Pistol50] = ("Pistol .50", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.SNSPistol] = ("SNS Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.SNSPistol_MK2] = ("SNS Pistol MK2", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Heavy_Pistol] = ("Heavy Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Vintage_Pistol] = ("Vintage Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Flare_Gun] = ("Flare Gun", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Marksman_Pistol] = ("Marksman Pistol", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Heavy_Revolver] = ("Heavy Revolver", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Heavy_Revolver_MK2] = ("Heavy Revolver MK2", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Double_Action] = ("Double Action", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Up_n_Atomizer] = ("Up-n-Atomizer", DamageGroup.Bullet, DamageType.Pistol),
                    [WeaponHash.Micro_SMG] = ("Micro SMG", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.SMG] = ("SMG", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.SMGMK2] = ("SMG MK2", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.Assault_SMG] = ("Assault SMG", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.Combat_PDW] = ("Combat PDW", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.Machine_Pistol] = ("Machine Pistol", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.Mini_SMG] = ("Mini SMG", DamageGroup.Bullet, DamageType.SMG),
                    [WeaponHash.Unholy_Hellbringer] = ("Unholy Hellbringer", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.Pump_Shotgun] = ("Pump Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Pump_Shotgun_MK2] = ("Pump Shotgun MK2", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Sawed_Off_Shotgun] = ("Sawed-Off Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Assault_Shotgun] = ("Assault Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Bullpup_Shotgun] = ("Bullpup Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Musket] = ("Musket", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.Heavy_Shotgun] = ("Heavy Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Double_Barrel_Shotgun] =
                        ("Double Barrel Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Sweeper_Shotgun] = ("Sweeper Shotgun", DamageGroup.Bullet, DamageType.Shotgun),
                    [WeaponHash.Assault_Rifle] = ("Assault Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Assault_Rifle_MK2] = ("Assault Rifle MK2", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Carbine_Rifle] = ("Carbine Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Carbine_Rifle_MK2] = ("Carbine Rifle MK2", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Advanced_Rifle] = ("Advanced Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Special_Carbine] = ("Special Carbine", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Special_Carbine_MK2] = ("Special Carbine MK2", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Bullpup_Rifle] = ("Bullpup Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Bullpup_Rifle_MK2] = ("Bullpup Rifle MK2", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.Compact_Rifle] = ("Compact Rifle", DamageGroup.Bullet, DamageType.Rifle),
                    [WeaponHash.MG] = ("MG", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.Combat_MG] = ("Combat MG", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.Combat_MGMK2] = ("Combat MG MK2", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.Gusenberg_Sweeper] = ("Gusenberg Sweeper", DamageGroup.Bullet, DamageType.MG),
                    [WeaponHash.Sniper_Rifle] = ("Sniper Rifle", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.Heavy_Sniper] = ("Heavy Sniper", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.Heavy_Sniper_MK2] = ("Heavy Sniper MK2", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.Marksman_Rifle] = ("Marksman Rifle", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.Marksman_Rifle_MK2] = ("Marksman Rifle MK2", DamageGroup.Bullet, DamageType.Sniper),
                    [WeaponHash.RPG] = ("RPG", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Grenade_Launcher] = ("Grenade Launcher", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Smoke_Grenade_Launcher] = ("Smoke Grenade Launcher", DamageGroup.NonDamaging,
                        DamageType.Launcher),
                    [WeaponHash.Minigun] = ("Minigun", DamageGroup.Bullet, DamageType.Launcher),
                    [WeaponHash.Firework_Launcher] = ("Firework Launcher", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Railgun] = ("Railgun", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Homing_Launcher] = ("Homing Launcher", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Compact_Grenade_Launcher] = ("Compact Grenade Launcher", DamageGroup.Explosion,
                        DamageType.Launcher),
                    [WeaponHash.Ray_Minigun] = ("Ray Minigun", DamageGroup.Bullet, DamageType.Launcher),
                    [WeaponHash.Grenade] = ("Grenade", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.BZGas] = ("BZ Gas", DamageGroup.Gas, DamageType.Gas),
                    [WeaponHash.Smoke_Grenade] =
                        ("Smoke Grenade", DamageGroup.NonDamaging, DamageType.ThrowableNonLethal),
                    [WeaponHash.Flare] = ("Flare", DamageGroup.NonDamaging, DamageType.ThrowableNonLethal),
                    [WeaponHash.Molotov] = ("Molotov", DamageGroup.Fire, DamageType.Fire),
                    [WeaponHash.Sticky_Bomb] = ("Sticky Bomb", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.Proximity_Mine] = ("Proximity Mine", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.Snowball] = ("Snowball", DamageGroup.NonDamaging, DamageType.ThrowableNonLethal),
                    [WeaponHash.Pipe_Bomb] = ("Pipe Bomb", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.Baseball] = ("Baseball", DamageGroup.NonDamaging, DamageType.ThrowableNonLethal),
                    [WeaponHash.Jerry_Can] = ("Jerry Can", DamageGroup.NonDamaging, DamageType.Misc),
                    [WeaponHash.Fire_Extinguisher] = ("Fire Extinguisher", DamageGroup.NonDamaging, DamageType.Misc),
                    [WeaponHash.Parachute] = ("Parachute", DamageGroup.Unknown, DamageType.Unknown),
                    [WeaponHash.Electric_Fence] = ("Electric Fence", DamageGroup.Environmental, DamageType.Electric),
                    [WeaponHash.Hitby_Water_Cannon] =
                        ("Hit by Water Cannon", DamageGroup.WaterCannon, DamageType.WaterCannon),
                    [WeaponHash.Rammedby_Car] = ("Rammed by Car", DamageGroup.Vehicle, DamageType.Vehicle),
                    [WeaponHash.Run_Overby_Car] = ("Run Over by Car", DamageGroup.Vehicle, DamageType.Vehicle),
                    [WeaponHash.Fall] = ("Fall", DamageGroup.Fall, DamageType.Fall),
                    [WeaponHash.Animal] = ("Animal", DamageGroup.Animal, DamageType.Animal),
                    [WeaponHash.Airstrike_Rocket] = ("Airstrike Rocket", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Bleeding] = ("Bleeding", DamageGroup.Medical, DamageType.Medical),
                    [WeaponHash.Briefcase] = ("Briefcase", DamageGroup.Unknown, DamageType.Unknown),
                    [WeaponHash.Briefcase02] = ("Briefcase 02", DamageGroup.Unknown, DamageType.Unknown),
                    [WeaponHash.Cougar] = ("Cougar", DamageGroup.Animal, DamageType.Animal),
                    [WeaponHash.Barbed_Wire] = ("Barbed Wire", DamageGroup.Environmental, DamageType.BarbedWire),
                    [WeaponHash.Drowning] = ("Drowning", DamageGroup.Drowning, DamageType.Drowning),
                    [WeaponHash.Drowning_In_Vehicle] =
                        ("Drowning In Vehicle", DamageGroup.Drowning, DamageType.Drowning),
                    [WeaponHash.Explosion] = ("Explosion", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.Exhaustion] = ("Exhaustion", DamageGroup.Medical, DamageType.Medical),
                    [WeaponHash.Fire] = ("Fire", DamageGroup.Fire, DamageType.Fire),
                    [WeaponHash.Heli_Crash] = ("Heli Crash", DamageGroup.Explosion, DamageType.Explosive),
                    [WeaponHash.Vehicle_Rocket] = ("Rocket", DamageGroup.Explosion, DamageType.Launcher),
                    [WeaponHash.Vehicle_Akula_Barrage] = ("Akula Barrage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Akula_Minigun] = ("Akula Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Akula_Missile] = ("Akula Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Akula_Turret_Dual] = ("Akula Turret Dual", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Akula_Turret_Single] = ("Akula Turret Single", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_APCCannon] = ("APC Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_APCMG] = ("APC MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_APCMissile] = ("APC Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Ardent_MG] =
                        ("Ardent MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Avenger_Cannon] = ("Avenger Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Barrage_Rear_GL] = ("Barrage Rear GL", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Barrage_Rear_MG] = ("Barrage Rear MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Barrage_Rear_Minigun] = ("Barrage Rear Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Barrage_Top_MG] = ("Barrage Top MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Barrage_Top_Minigun] = ("Barrage Top Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Bombushka_Cannon] = ("Bombushka Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Bombushka_Dual_MG] = ("Bombushka Dual MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Cannon_Blazer] = ("Cannon Blazer", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Caracara_MG] =
                        ("Caracara MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Caracara_Minigun] = ("Caracara Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Cherno_Missile] = ("Cherno Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Comet_MG] = ("Comet MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Deluxo_MG] =
                        ("Deluxo MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Deluxo_Missile] = ("Deluxo Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Dogfighter_MG] = ("Dogfighter MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Dogfighter_Missile] = ("Dogfighter Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Dune_Grenade_Launcher] = ("Dune Grenade Launcher",
                        DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Dune_MG] = ("Dune MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Dune_Minigun] =
                        ("Dune Minigun", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Enemy_Laser] = ("Enemy Laser", DamageGroup.Unknown, DamageType.Unknown),
                    [WeaponHash.Vehicle_Hacker_Missile] = ("Hacker Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Hacker_Missile_Homing] = ("Hacker Missile Homing",
                        DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Halftrack_Dual_MG] = ("Halftrack Dual MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Halftrack_Quad_MG] = ("Halftrack Quad MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Havok_Minigun] = ("Havok Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Hunter_Barrage] = ("Hunter Barrage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Hunter_Cannon] = ("Hunter Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Hunter_MG] =
                        ("Hunter MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Hunter_Missile] = ("Hunter Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Insurgent_Minigun] = ("Insurgent Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Khanjali_Cannon] = ("Khanjali Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Khanjali_Cannon_Heavy] = ("Khanjali Cannon Heavy",
                        DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Khanjali_GL] = ("Khanjali GL", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Khanjali_MG] =
                        ("Khanjali MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Menacer_MG] =
                        ("Menacer MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Microlight_MG] = ("Microlight MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Mobileops_Cannon] = ("Mobileops Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Mogul_Dual_Nose] = ("Mogul Dual Nose", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Mogul_Dual_Turret] = ("Mogul Dual Turret", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Mogul_Nose] =
                        ("Mogul Nose", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Mogul_Turret] =
                        ("Mogul Turret", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Mule4MG] = ("Mule4 MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Mule4Missile] = ("Mule4 Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Mule4Turret_GL] = ("Mule4 Turret GL", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Nightshark_MG] = ("Nightshark MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Nose_Turret_Valkyrie] = ("Nose Turret Valkyrie", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Oppressor_MG] =
                        ("Oppressor MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Oppressor_Missile] = ("Oppressor Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Oppressor2Cannon] = ("Oppressor2 Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Oppressor2MG] = ("Oppressor2 MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Oppressor2Missile] = ("Oppressor2 Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Plane_Rocket] = ("Plane Rocket", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Player_Buzzard] = ("Player Buzzard", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Player_Lazer] = ("Player Lazer", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Player_Savage] = ("Player Savage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Pounder2Barrage] = ("Pounder2 Barrage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Pounder2GL] = ("Pounder2 GL", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Pounder2Mini] = ("Pounder2 Mini", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Pounder2Missile] = ("Pounder2 Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Radar] = ("Radar", DamageGroup.NonDamaging, DamageType.NonDamaging),
                    [WeaponHash.Vehicle_Revolter_MG] =
                        ("Revolter MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Rogue_Cannon] = ("Rogue Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Rogue_MG] = ("Rogue MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Rogue_Missile] = ("Rogue Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Ruiner_Bullet] = ("Ruiner Bullet", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Ruiner_Rocket] = ("Ruiner Rocket", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Savestra_MG] =
                        ("Savestra MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Scramjet_MG] =
                        ("Scramjet MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Scramjet_Missile] = ("Scramjet Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Seabreeze_MG] =
                        ("Seabreeze MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Searchlight] = ("Searchlight", DamageGroup.NonDamaging,
                        DamageType.NonDamaging),
                    [WeaponHash.Vehicle_Space_Rocket] = ("Space Rocket", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Speedo4MG] =
                        ("Speedo4 MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Speedo4Turret_MG] = ("Speedo4 Turret MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Speedo4Turret_Mini] = ("Speedo4 Turret Mini", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Strikeforce_Barrage] = ("Strikeforce Barrage", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Strikeforce_Cannon] = ("Strikeforce Cannon", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Strikeforce_Missile] = ("Strikeforce Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Subcar_MG] =
                        ("Subcar MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Subcar_Missile] = ("Subcar Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Subcar_Torpedo] = ("Subcar Torpedo", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Tampa_Dual_Minigun] = ("Tampa Dual Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Tampa_Fixed_Minigun] = ("Tampa Fixed Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Tampa_Missile] = ("Tampa Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Tampa_Mortar] = ("Tampa Mortar", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Tank] = ("Tank", DamageGroup.Explosion, DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Technical_Minigun] = ("Technical Minigun", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Thruster_MG] =
                        ("Thruster MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Thruster_Missile] = ("Thruster Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Trailer_Dualaa] = ("Trailer Dualaa", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Trailer_Missile] = ("Trailer Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Trailer_Quad_MG] = ("Trailer Quad MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Tula_Dual_MG] =
                        ("Tula Dual MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Tula_MG] = ("Tula MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Tula_Minigun] =
                        ("Tula Minigun", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Tula_Nose_MG] =
                        ("Tula Nose MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Turret_Boxville] = ("Turret Boxville", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Turret_Insurgent] = ("Turret Insurgent", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Turret_Limo] =
                        ("Turret Limo", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Turret_Technical] = ("Turret Technical", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Turret_Valkyrie] = ("Turret Valkyrie", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Vigilante_MG] =
                        ("Vigilante MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Vigilante_Missile] = ("Vigilante Missile", DamageGroup.Explosion,
                        DamageType.VehicleLauncher),
                    [WeaponHash.Vehicle_Viseris_MG] =
                        ("Viseris MG", DamageGroup.Bullet, DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Volatol_Dual_MG] = ("Volatol Dual MG", DamageGroup.Bullet,
                        DamageType.VehicleFirearm),
                    [WeaponHash.Vehicle_Water_Cannon] = ("Water Cannon", DamageGroup.WaterCannon,
                        DamageType.WaterCannon),
                    [WeaponHash.Vehicle_Helicopter_Rotors] =
                        ("Helicopter Rotors", DamageGroup.Vehicle, DamageType.Vehicle)
                };
    };
}